/**
 * Page-side service-worker registration.  Pairs with the workbox SW
 * generated by `vite-plugin-pwa` (config in `vite.config.ts`).
 *
 * # Offline-replay strategy
 *
 * Outbox replay deliberately lives in the page, not the SW.  The
 * orchestrator (`src/client/sync/orchestrator.ts`) owns:
 *   - Dexie outbox draining → POST /api/v1/sync/operations
 *   - cursor backfill via POST /api/v1/sync/cursor
 *   - exponential backoff, navigator.locks single-leader, and the
 *     UI-visible flash + toast bus on rollback.
 *
 * The SW's role is narrower: precache the app shell so a first launch
 * with no network shows the UI, and runtime-cache public immutable
 * portrait/cover images. Authenticated API GETs are never cached;
 * a brand-new device needs its first online data download. The SW never
 * caches mutations, never replays POSTs, and never replays sync ops —
 * that is page-orchestrator territory.
 *
 * # Update discovery
 *
 * `registerType: 'autoUpdate'` only means the new worker takes over
 * without waiting; it does NOT reload the page, and the browser only
 * re-checks for a new worker on navigation.  This app is a SPA whose
 * router never navigates, so a tab left open for days would run stale
 * JS against fresh precached assets forever and never say so.  We
 * therefore poll `registration.update()` on an interval and whenever
 * the tab regains focus or the network returns, then surface the
 * result: a `gpc:sw-update-ready` CustomEvent carrying a `reload()`,
 * plus `getPendingSwUpdate()` for subscribers that mount after the
 * event fired.  It is safe to import in tests / non-browser contexts —
 * all DOM access is feature-detected.
 */

import { connectionStore } from '../client/lib/connectionState.ts';

const UPDATE_READY_EVENT = 'gpc:sw-update-ready';
const CONTROLLER_CHANGED_EVENT = 'gpc:sw-controller-changed';
const CLIENT_OUTDATED_EVENT = 'gpc:client-outdated';

/** How often a foreground tab re-checks for a new build. */
export const SW_UPDATE_POLL_MS = 60 * 60 * 1000;
/** Floor between checks, so focus/online churn can't hammer the server. */
const MIN_CHECK_GAP_MS = 5 * 60 * 1000;

export interface SwLifecycleEvents {
  /** A new SW has installed and is waiting to take over. */
  onUpdateReady?(reload: () => void): void;
  /** The active SW changed (i.e. the new one took over). */
  onControllerChanged?(): void;
}

/**
 * Latched so a subscriber that mounts *after* the update was found
 * still learns about it.  `registerSwLifecycle()` runs at module load,
 * before React renders, so the toast component would otherwise miss an
 * update discovered during startup.
 */
let pendingUpdate: (() => void) | null = null;

/**
 * The worker we've already told the user about.  Kept separately from
 * `pendingUpdate` so dismissing the prompt re-enables polling (see
 * `dismissPendingSwUpdate`) without immediately re-announcing the same
 * build on the next tick.
 */
let announcedWorker: ServiceWorker | null = null;

/** The reload callback for an already-discovered update, if any. */
export function getPendingSwUpdate(): (() => void) | null {
  return pendingUpdate;
}

/**
 * The user dismissed the prompt instead of reloading.  Drops the
 * outstanding announcement so update checks resume — otherwise
 * `checkForUpdate`'s `if (pendingUpdate) return` guard would latch
 * closed and this tab would never look for a release again. The
 * *announced worker* is remembered, so polling won't nag about the
 * same build; a genuinely newer one still gets through.
 */
export function dismissPendingSwUpdate(): void {
  pendingUpdate = null;
}

/** Test seam: forget both the announcement and the acknowledgement. */
export function clearPendingSwUpdate(): void {
  pendingUpdate = null;
  announcedWorker = null;
}

function makeReload(worker: ServiceWorker | null): () => void {
  return () => {
    // Harmless when the SW already skipped waiting (autoUpdate does),
    // and necessary when it hasn't.
    worker?.postMessage({ type: 'SKIP_WAITING' });
    // Give the SW a tick to take over, then reload.  A reload is what
    // actually swaps the running JS; activation alone does not.
    setTimeout(() => window.location.reload(), 250);
  };
}

/**
 * Wire the SW lifecycle into the app.  Idempotent; safe to call
 * multiple times.  Returns a teardown that detaches listeners (used
 * in tests).
 */
export function registerSwLifecycle(events: SwLifecycleEvents = {}): () => void {
  if (typeof window === 'undefined' || typeof navigator === 'undefined') {
    return () => {};
  }
  if (!('serviceWorker' in navigator)) {
    return () => {};
  }

  const announceUpdate = (worker: ServiceWorker | null) => {
    // Already told the user about this exact build and they dismissed
    // it -- don't re-nag on the next poll.
    if (worker !== null && worker === announcedWorker) return;
    const reload = makeReload(worker);
    pendingUpdate = reload;
    announcedWorker = worker;
    window.dispatchEvent(new CustomEvent(UPDATE_READY_EVENT, { detail: { reload } }));
    events.onUpdateReady?.(reload);
  };

  const onMessage = (e: MessageEvent) => {
    if (e?.data?.type === 'SKIP_WAITING_DONE') {
      window.dispatchEvent(new CustomEvent(CONTROLLER_CHANGED_EVENT));
      events.onControllerChanged?.();
    }
  };

  const onControllerChange = () => {
    window.dispatchEvent(new CustomEvent(CONTROLLER_CHANGED_EVENT));
    events.onControllerChanged?.();
  };

  navigator.serviceWorker.addEventListener('message', onMessage);
  navigator.serviceWorker.addEventListener('controllerchange', onControllerChange);

  let registration: ServiceWorkerRegistration | null = null;
  let lastCheckAt = 0;
  let pollTimer: ReturnType<typeof setInterval> | null = null;

  /**
   * Announce `worker` once it finishes installing (or right away if it
   * already has).  Extracted so the startup path can adopt a worker
   * that was **already installing** before our async registration
   * lookup resolved: `updatefound` would have fired with no listener
   * attached, `waiting` is still null so the startup check below misses
   * it too, and once autoUpdate activates it no later
   * `registration.update()` can recreate the lost event — that release
   * would never prompt at all.
   */
  const watchInstalling = (worker: ServiceWorker) => {
    const check = () => {
      if (worker.state === 'installed' && navigator.serviceWorker.controller) {
        announceUpdate(worker);
      }
    };
    worker.addEventListener('statechange', check);
    check();
  };

  const onUpdateFound = () => {
    if (!registration) return;
    const installing = registration.installing;
    if (!installing) return;
    watchInstalling(installing);
  };

  const checkForUpdate = (force = false) => {
    if (!registration) return;
    // An announcement the user hasn't acted on yet -- nothing to learn
    // until they reload or dismiss it.
    if (pendingUpdate) return;
    const now = Date.now();
    if (!force && now - lastCheckAt < MIN_CHECK_GAP_MS) return;
    if (!connectionStore.canAttemptNetwork()) return;
    lastCheckAt = now;
    // A worker that installed while the prompt was dismissed is parked
    // in `waiting` and won't fire `updatefound` again; announceUpdate
    // no-ops if it's the build we already showed.
    if (registration.waiting && navigator.serviceWorker.controller) {
      announceUpdate(registration.waiting);
    }
    void registration.update().catch(() => {
      // Offline or the server is down -- the next tick tries again.
    });
  };

  const onFocus = () => checkForUpdate();
  const onOnline = () => checkForUpdate();
  const onVisibility = () => {
    if (document.visibilityState === 'visible') checkForUpdate();
  };

  let disposed = false;

  // On a first visit there is no registration yet: vite-plugin-pwa's
  // injected script registers the worker on the window `load` event,
  // well after this module runs. `getRegistration()` resolves to null
  // there, so bailing out would leave that tab with no polling and no
  // listeners for the rest of its life -- it would never offer an
  // update until someone reloaded it by hand. `ready` resolves once a
  // registration becomes active; it simply stays pending when the app
  // runs without a service worker (dev), which is the correct no-op.
  const resolveRegistration = async (): Promise<ServiceWorkerRegistration | null> => {
    const existing = await navigator.serviceWorker.getRegistration();
    if (existing) return existing;
    return await navigator.serviceWorker.ready;
  };

  void resolveRegistration().then((reg) => {
    if (!reg || disposed) return;
    registration = reg;
    reg.addEventListener('updatefound', onUpdateFound);

    // An update installed by another tab (or a previous session) is
    // already parked in `waiting` and will never fire `updatefound`
    // here -- without this branch that update stays invisible.
    //
    // Announce it but keep going: returning early here would skip the
    // polling setup below, so a tab that started with a waiting worker
    // would never check for anything again once the user dismissed it.
    if (reg.waiting && navigator.serviceWorker.controller) {
      announceUpdate(reg.waiting);
    } else if (reg.installing) {
      // A navigation-triggered update that began before this lookup
      // resolved: `updatefound` already fired with nobody listening.
      watchInstalling(reg.installing);
    }

    lastCheckAt = Date.now();
    pollTimer = setInterval(() => checkForUpdate(), SW_UPDATE_POLL_MS);
    window.addEventListener('focus', onFocus);
    window.addEventListener('online', onOnline);
    document.addEventListener('visibilitychange', onVisibility);
  });

  return () => {
    disposed = true;
    navigator.serviceWorker.removeEventListener('message', onMessage);
    navigator.serviceWorker.removeEventListener('controllerchange', onControllerChange);
    window.removeEventListener('focus', onFocus);
    window.removeEventListener('online', onOnline);
    document.removeEventListener('visibilitychange', onVisibility);
    if (pollTimer) clearInterval(pollTimer);
    pollTimer = null;
    if (registration) {
      registration.removeEventListener('updatefound', onUpdateFound);
    }
  };
}

/*
 * # Forced update
 *
 * The prompt above leaves reloading to the user because nothing breaks while
 * they wait. A server that refuses this build's sync protocol (HTTP 426, see
 * `shared/syncProtocol.ts`) is different: queued edits cannot be sent until
 * the page runs the current build, so the update is no longer optional.
 */

/** sessionStorage key: when this tab last forced a reload for a 426. */
const FORCED_RELOAD_KEY = 'gpc:forced-update-reload-at';
/** A tab that is still outdated right after a forced reload waits this long before trying again. */
export const FORCED_RELOAD_MIN_INTERVAL_MS = 60_000;
const SW_STEP_TIMEOUT_MS = 10_000;
/** Pause after the user leaves an input so its blur commit reaches the outbox. */
const EDIT_SETTLE_MS = 500;

export interface ForcedUpdateOptions {
  reload?: () => void;
  now?: () => number;
}

let forcedUpdateStarted = false;

/** Test seam. */
export function resetForcedUpdateForTests(): void {
  forcedUpdateStarted = false;
}

function readForcedReloadAt(): number {
  try {
    return Number(window.sessionStorage.getItem(FORCED_RELOAD_KEY) ?? 0) || 0;
  } catch {
    return 0;
  }
}

function writeForcedReloadAt(at: number): void {
  try {
    window.sessionStorage.setItem(FORCED_RELOAD_KEY, String(at));
  } catch {
    // Storage unavailable: the in-memory latch still prevents repeats in this page.
  }
}

function withTimeout<T>(promise: Promise<T>, ms: number): Promise<T | undefined> {
  return Promise.race([
    promise,
    new Promise<undefined>((resolve) => setTimeout(() => resolve(undefined), ms)),
  ]);
}

function waitForActivation(worker: ServiceWorker): Promise<void> {
  return new Promise((resolve) => {
    if (worker.state === 'activated' || worker.state === 'redundant') return resolve();
    const onChange = () => {
      if (worker.state === 'activated' || worker.state === 'redundant') {
        worker.removeEventListener('statechange', onChange);
        resolve();
      }
    };
    worker.addEventListener('statechange', onChange);
    worker.postMessage({ type: 'SKIP_WAITING' });
  });
}

/** Fetch and activate the newest worker so the reload runs the current build. */
async function activateLatestWorker(): Promise<void> {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return;
  const registration = await navigator.serviceWorker.getRegistration();
  if (!registration) return;
  await withTimeout(
    registration.update().catch(() => undefined),
    SW_STEP_TIMEOUT_MS,
  );
  const worker = registration.installing ?? registration.waiting;
  if (worker) await withTimeout(waitForActivation(worker), SW_STEP_TIMEOUT_MS);
}

function editingElement(): Element | null {
  const active = typeof document === 'undefined' ? null : document.activeElement;
  if (!active) return null;
  if (active instanceof HTMLElement && active.isContentEditable) return active;
  return active.matches('input, textarea, select') ? active : null;
}

/**
 * Resolve once no input has focus. An uncommitted draft only reaches the
 * outbox on blur (`useDraftField`), so reloading under a focused input would
 * discard what the user is typing.
 */
function waitUntilNotEditing(): Promise<void> {
  return new Promise((resolve) => {
    const check = () => {
      if (editingElement()) return;
      document.removeEventListener('focusout', onFocusOut, true);
      setTimeout(() => (editingElement() ? arm() : resolve()), EDIT_SETTLE_MS);
    };
    const onFocusOut = () => setTimeout(check, 0);
    const arm = () => document.addEventListener('focusout', onFocusOut, true);
    if (!editingElement()) {
      setTimeout(() => (editingElement() ? arm() : resolve()), 0);
      return;
    }
    arm();
  });
}

/**
 * Force this tab onto the current build: announce it, activate the newest
 * service worker, wait until the user is not mid-edit, then reload. Queued
 * outbox operations stay in IndexedDB and are sent by the new build.
 *
 * Returns false without reloading when this tab already force-reloaded within
 * `FORCED_RELOAD_MIN_INTERVAL_MS` (the server may still be mid-deploy), which
 * prevents a reload loop; the caller retries after that window.
 */
export function requestClientUpdate(options: ForcedUpdateOptions = {}): boolean {
  if (typeof window === 'undefined') return false;
  if (forcedUpdateStarted) return true;
  const now = options.now ?? Date.now;
  window.dispatchEvent(new CustomEvent(CLIENT_OUTDATED_EVENT));
  if (now() - readForcedReloadAt() < FORCED_RELOAD_MIN_INTERVAL_MS) return false;
  forcedUpdateStarted = true;
  const reload = options.reload ?? (() => window.location.reload());
  void (async () => {
    try {
      await activateLatestWorker();
    } catch {
      // The reload still fetches the newest shell when the network allows.
    }
    await waitUntilNotEditing();
    writeForcedReloadAt(now());
    reload();
  })();
  return true;
}

export const swEvents = {
  UPDATE_READY: UPDATE_READY_EVENT,
  CONTROLLER_CHANGED: CONTROLLER_CHANGED_EVENT,
  CLIENT_OUTDATED: CLIENT_OUTDATED_EVENT,
} as const;
