/**
 * Characterization tests for src/server/routes/history.ts
 * (per-character and per-campaign audit history feeds).
 *
 * These pin CURRENT behavior ahead of a refactor — not a spec for what the
 * routes "should" do.
 *
 * Requires a running Postgres test DB at the URL in testConfig below.
 */

import { describe, expect, it } from 'bun:test';
import { createApp } from '../app.ts';
import { type AppConfig, resetConfigCache } from '../config.ts';

const testConfig: AppConfig = {
  environment: 'test',
  port: 0,
  host: '127.0.0.1',
  databaseUrl: 'postgres://gurps:gurps@localhost:5432/gurps',
  jwtSecret: 'test-secret-which-is-deliberately-very-long-and-not-a-placeholder',
  jwtAccessTtlMinutes: 15,
  jwtRefreshTtlDays: 14,
  apiKeyPepper: 'test-secret-which-is-deliberately-very-long-and-not-a-placeholder',
  corsOrigins: [],
  resendApiKey: undefined,
  resendFromEmail: undefined,
  appBaseUrl: undefined,
};

process.env.DATABASE_URL = testConfig.databaseUrl;
process.env.JWT_SECRET = testConfig.jwtSecret;
process.env.ENVIRONMENT = testConfig.environment;
resetConfigCache();

const app = createApp(testConfig);

function bearer(token: string) {
  return { Authorization: `Bearer ${token}` };
}

function jsonHeaders(token: string) {
  return { ...bearer(token), 'content-type': 'application/json' };
}

async function registerUser(suffix: string) {
  const email = `history-test-${suffix}-${Date.now()}-${Math.random().toString(36).slice(2)}@example.com`;
  const res = await app.request('/api/v1/auth/register', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ email, password: 'TestPassword1!', displayName: `Test ${suffix}` }),
  });
  const body = (await res.json()) as { accessToken: string };
  return { accessToken: body.accessToken, email, displayName: `Test ${suffix}` };
}

async function createCampaign(
  accessToken: string,
  overrides: Record<string, unknown> = {},
): Promise<Record<string, unknown>> {
  const res = await app.request('/api/v1/campaigns', {
    method: 'POST',
    headers: jsonHeaders(accessToken),
    body: JSON.stringify({ name: `Camp ${Date.now()}-${Math.random()}`, ...overrides }),
  });
  return (await res.json()) as Record<string, unknown>;
}

async function addMember(ownerToken: string, campaignId: string, email: string) {
  const res = await app.request(`/api/v1/campaigns/${campaignId}/members`, {
    method: 'POST',
    headers: jsonHeaders(ownerToken),
    body: JSON.stringify({ email }),
  });
  expect(res.status).toBe(200);
}

async function createCharacter(
  accessToken: string,
  overrides: Record<string, unknown> = {},
): Promise<Record<string, unknown>> {
  const res = await app.request('/api/v1/characters', {
    method: 'POST',
    headers: jsonHeaders(accessToken),
    body: JSON.stringify({ name: `Character ${Date.now()}-${Math.random()}`, ...overrides }),
  });
  expect(res.status).toBe(201);
  return (await res.json()) as Record<string, unknown>;
}

type HistoryEvent = {
  id: string;
  revision: number;
  scope: string;
  entityClass: string;
  op: string;
  actorUserId: string | null;
  actorDisplayName: string | null;
  summary: string;
  oldRow?: Record<string, unknown> | null;
  newRow?: Record<string, unknown> | null;
};

// ===================== CHARACTER HISTORY =====================

describe('GET /characters/{id}/history', () => {
  it('owner sees every event generated by a sequence of REST edits, newest first', async () => {
    const owner = await registerUser('char-owner');
    const character = await createCharacter(owner.accessToken, { name: 'Chronicle' });

    await app.request(`/api/v1/characters/${character.id}`, {
      method: 'PATCH',
      headers: jsonHeaders(owner.accessToken),
      body: JSON.stringify({ name: 'Chronicle Renamed' }),
    });
    const traitRes = await app.request(`/api/v1/characters/${character.id}/traits`, {
      method: 'POST',
      headers: jsonHeaders(owner.accessToken),
      body: JSON.stringify({ kind: 'advantage', name: 'Luck' }),
    });
    const { trait } = (await traitRes.json()) as { trait: { id: string } };
    await app.request(`/api/v1/characters/${character.id}/traits/${trait.id}`, {
      method: 'PATCH',
      headers: jsonHeaders(owner.accessToken),
      body: JSON.stringify({ points: 15 }),
    });
    await app.request(`/api/v1/characters/${character.id}/traits/${trait.id}`, {
      method: 'DELETE',
      headers: bearer(owner.accessToken),
    });

    const res = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(owner.accessToken),
    });
    expect(res.status).toBe(200);
    const events = (await res.json()) as HistoryEvent[];
    // insert character, update character, insert trait, update trait, delete trait.
    expect(events.length).toBe(5);
    // Newest first.
    expect(events[0]?.op).toBe('delete');
    expect(events[0]?.entityClass).toBe('character_trait');
    expect(events[events.length - 1]?.op).toBe('insert');
    expect(events[events.length - 1]?.entityClass).toBe('character');
    for (const e of events) {
      expect(typeof e.summary).toBe('string');
      expect(e.summary.length).toBeGreaterThan(0);
      expect(e.actorDisplayName).toBe(owner.displayName);
    }
    // Descending revision order.
    for (let i = 1; i < events.length; i++) {
      const prev = events[i - 1];
      const curr = events[i];
      expect(prev).toBeDefined();
      expect(curr).toBeDefined();
      expect(prev?.revision).toBeGreaterThan(curr?.revision ?? Number.NaN);
    }
  });

  it('a member with minimal access (shareCharacterSheets=false) is denied (403)', async () => {
    const gm = await registerUser('char-hist-gm');
    const owner = await registerUser('char-hist-owner');
    const viewer = await registerUser('char-hist-viewer');
    const campaign = await createCampaign(gm.accessToken, { shareCharacterSheets: false });
    await addMember(gm.accessToken, campaign.id as string, owner.email);
    await addMember(gm.accessToken, campaign.id as string, viewer.email);
    const character = await createCharacter(owner.accessToken, {
      name: 'Hidden',
      campaignId: campaign.id,
    });

    const res = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(viewer.accessToken),
    });
    expect(res.status).toBe(403);
  });

  it('a member with full access (shareCharacterSheets=true) and the GM can both read history', async () => {
    const gm = await registerUser('char-hist-full-gm');
    const owner = await registerUser('char-hist-full-owner');
    const viewer = await registerUser('char-hist-full-viewer');
    const campaign = await createCampaign(gm.accessToken, { shareCharacterSheets: true });
    await addMember(gm.accessToken, campaign.id as string, owner.email);
    await addMember(gm.accessToken, campaign.id as string, viewer.email);
    const character = await createCharacter(owner.accessToken, {
      name: 'Visible',
      campaignId: campaign.id,
    });

    const viewerRes = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(viewer.accessToken),
    });
    expect(viewerRes.status).toBe(200);
    const viewerEvents = (await viewerRes.json()) as HistoryEvent[];
    expect(viewerEvents.length).toBeGreaterThan(0);

    const gmRes = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(gm.accessToken),
    });
    expect(gmRes.status).toBe(200);
  });

  it('a non-member of the campaign is denied (403)', async () => {
    const owner = await registerUser('char-hist-nonmember-owner');
    const outsider = await registerUser('char-hist-nonmember-outsider');
    const campaign = await createCampaign(owner.accessToken, { shareCharacterSheets: true });
    const character = await createCharacter(owner.accessToken, {
      name: 'Guarded',
      campaignId: campaign.id,
    });
    const res = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(outsider.accessToken),
    });
    expect(res.status).toBe(403);
  });

  it('a non-owner requesting a campaignless character is denied (403)', async () => {
    const owner = await registerUser('char-hist-solo-owner');
    const outsider = await registerUser('char-hist-solo-outsider');
    const character = await createCharacter(owner.accessToken, { name: 'Solo' });
    const res = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(outsider.accessToken),
    });
    expect(res.status).toBe(403);
  });

  it('404s for a nonexistent character', async () => {
    const owner = await registerUser('char-hist-404');
    const res = await app.request(
      '/api/v1/characters/00000000-0000-0000-0000-000000000000/history',
      { headers: bearer(owner.accessToken) },
    );
    expect(res.status).toBe(404);
  });
});

// ===================== CAMPAIGN HISTORY =====================

describe('GET /campaigns/{id}/history', () => {
  it('owner sees campaign-scope events, newest first, after a settings change', async () => {
    const owner = await registerUser('camp-hist-owner');
    const campaign = await createCampaign(owner.accessToken, { name: 'Original Name' });
    const patchRes = await app.request(`/api/v1/campaigns/${campaign.id}`, {
      method: 'PATCH',
      headers: jsonHeaders(owner.accessToken),
      body: JSON.stringify({ name: 'Renamed Campaign' }),
    });
    expect(patchRes.status).toBe(200);

    const res = await app.request(`/api/v1/campaigns/${campaign.id}/history`, {
      headers: bearer(owner.accessToken),
    });
    expect(res.status).toBe(200);
    const events = (await res.json()) as HistoryEvent[];
    // campaign insert + owner membership insert + the rename update = 3.
    expect(events.length).toBe(3);
    expect(events[0]?.op).toBe('update');
    expect(events[0]?.entityClass).toBe('campaign');
    expect(events.every((e) => e.scope === 'campaign')).toBe(true);
    // No detail requested: oldRow/newRow are absent from the payload.
    expect(events[0]?.oldRow).toBeUndefined();
    expect(events[0]?.newRow).toBeUndefined();
  });

  it('?detail=1 includes oldRow/newRow snapshots; ?detail=false does NOT (only explicit truthy tokens enable it)', async () => {
    const owner = await registerUser('camp-hist-detail');
    const campaign = await createCampaign(owner.accessToken, { name: 'Detail Test' });
    await app.request(`/api/v1/campaigns/${campaign.id}`, {
      method: 'PATCH',
      headers: jsonHeaders(owner.accessToken),
      body: JSON.stringify({ name: 'Detail Test Renamed' }),
    });

    const detailRes = await app.request(`/api/v1/campaigns/${campaign.id}/history?detail=1`, {
      headers: bearer(owner.accessToken),
    });
    const detailEvents = (await detailRes.json()) as HistoryEvent[];
    const renameEvent = detailEvents.find((e) => e.op === 'update' && e.entityClass === 'campaign');
    expect(renameEvent).toBeDefined();
    expect(renameEvent?.oldRow).toBeTruthy();
    expect(renameEvent?.newRow).toBeTruthy();
    expect((renameEvent?.newRow as Record<string, unknown>).name).toBe('Detail Test Renamed');
    expect((renameEvent?.oldRow as Record<string, unknown>).name).toBe('Detail Test');

    // Pinning a deliberate quirk documented in the query-param schema: the
    // string "false" is truthy for a plain non-empty check, so a naive
    // coercion would turn ?detail=false into detail=true. The route uses an
    // explicit allow-list ('1' | 'true' | 'yes'), so "false" stays OFF.
    const falseDetailRes = await app.request(
      `/api/v1/campaigns/${campaign.id}/history?detail=false`,
      { headers: bearer(owner.accessToken) },
    );
    const falseDetailEvents = (await falseDetailRes.json()) as HistoryEvent[];
    expect(falseDetailEvents[0]?.oldRow).toBeUndefined();
    expect(falseDetailEvents[0]?.newRow).toBeUndefined();
  });

  it('before pagination walks older pages without gaps or overlaps', async () => {
    const owner = await registerUser('camp-hist-page');
    const campaign = await createCampaign(owner.accessToken, { name: 'Page Test' });
    // 3 additional update events on top of the 2 creation events (campaign
    // insert + owner membership insert) = 5 total campaign-scope events.
    for (let i = 0; i < 3; i++) {
      await app.request(`/api/v1/campaigns/${campaign.id}`, {
        method: 'PATCH',
        headers: jsonHeaders(owner.accessToken),
        body: JSON.stringify({ name: `Page Test ${i}` }),
      });
    }

    const seen: HistoryEvent[] = [];
    let before: number | undefined;
    for (let page = 0; page < 10; page++) {
      const url = before
        ? `/api/v1/campaigns/${campaign.id}/history?limit=2&before=${before}`
        : `/api/v1/campaigns/${campaign.id}/history?limit=2`;
      const res = await app.request(url, { headers: bearer(owner.accessToken) });
      expect(res.status).toBe(200);
      const events = (await res.json()) as HistoryEvent[];
      if (events.length === 0) break;
      seen.push(...events);
      before = events[events.length - 1]?.revision;
      if (events.length < 2) break;
    }

    expect(seen.length).toBe(5);
    const ids = seen.map((e) => e.id);
    expect(new Set(ids).size).toBe(5); // no duplicates across pages.
    for (let i = 1; i < seen.length; i++) {
      const prev = seen[i - 1];
      const curr = seen[i];
      expect(prev).toBeDefined();
      expect(curr).toBeDefined();
      expect(prev?.revision).toBeGreaterThan(curr?.revision ?? Number.NaN);
    }
  });

  it('scope=character is GM-only: the owner can request it, a plain member is denied (403)', async () => {
    const gm = await registerUser('camp-hist-scope-gm');
    const player = await registerUser('camp-hist-scope-player');
    const campaign = await createCampaign(gm.accessToken);
    await addMember(gm.accessToken, campaign.id as string, player.email);
    const character = await createCharacter(player.accessToken, {
      name: 'Player Character',
      campaignId: campaign.id,
    });
    await app.request(`/api/v1/characters/${character.id}`, {
      method: 'PATCH',
      headers: jsonHeaders(player.accessToken),
      body: JSON.stringify({ name: 'Player Character Renamed' }),
    });

    const gmRes = await app.request(`/api/v1/campaigns/${campaign.id}/history?scope=character`, {
      headers: bearer(gm.accessToken),
    });
    expect(gmRes.status).toBe(200);
    const gmEvents = (await gmRes.json()) as HistoryEvent[];
    expect(gmEvents.every((e) => e.scope === 'character')).toBe(true);
    expect(gmEvents.some((e) => e.entityClass === 'character')).toBe(true);

    const playerRes = await app.request(
      `/api/v1/campaigns/${campaign.id}/history?scope=character`,
      { headers: bearer(player.accessToken) },
    );
    expect(playerRes.status).toBe(403);
  });

  it('a non-member is denied (403)', async () => {
    const owner = await registerUser('camp-hist-nonmember-owner');
    const outsider = await registerUser('camp-hist-nonmember-outsider');
    const campaign = await createCampaign(owner.accessToken);
    const res = await app.request(`/api/v1/campaigns/${campaign.id}/history`, {
      headers: bearer(outsider.accessToken),
    });
    expect(res.status).toBe(403);
  });
});
