/**
 * Characterization tests for src/server/routes/history.ts
 * (per-character and per-campaign audit history feeds).
 *
 * These pin CURRENT behavior ahead of a refactor — not a spec for what the
 * routes "should" do.
 *
 * Requires a running Postgres test DB configured by ../testConfig.ts.
 */

import { describe, expect, it } from 'bun:test';
import { sql } from 'drizzle-orm';
import { createApp } from '../app.ts';
import { getDb } from '../db/client.ts';
import { entityHistory } from '../db/schema.ts';
import { configureIntegrationTestEnvironment, integrationTestConfig } from '../testConfig.ts';

configureIntegrationTestEnvironment();

const app = createApp(integrationTestConfig);

function bearer(token: string) {
  return { Authorization: `Bearer ${token}` };
}

function jsonHeaders(token: string) {
  return { ...bearer(token), 'content-type': 'application/json' };
}

async function registerUser(suffix: string) {
  const email = `history-test-${suffix}-${Date.now()}-${Math.random().toString(36).slice(2)}@example.com`;
  const res = await app.request('/api/v1/auth/register', {
    method: 'POST',
    headers: { 'content-type': 'application/json' },
    body: JSON.stringify({ email, password: 'TestPassword1!', displayName: `Test ${suffix}` }),
  });
  const body = (await res.json()) as { accessToken: string };
  return { accessToken: body.accessToken, email, displayName: `Test ${suffix}` };
}

async function createCampaign(
  accessToken: string,
  overrides: Record<string, unknown> = {},
): Promise<Record<string, unknown>> {
  const res = await app.request('/api/v1/campaigns', {
    method: 'POST',
    headers: jsonHeaders(accessToken),
    body: JSON.stringify({ name: `Camp ${Date.now()}-${Math.random()}`, ...overrides }),
  });
  return (await res.json()) as Record<string, unknown>;
}

async function addMember(ownerToken: string, campaignId: string, email: string) {
  const res = await app.request(`/api/v1/campaigns/${campaignId}/members`, {
    method: 'POST',
    headers: jsonHeaders(ownerToken),
    body: JSON.stringify({ email }),
  });
  expect(res.status).toBe(200);
}

async function addManager(ownerToken: string, campaignId: string, email: string) {
  await addMember(ownerToken, campaignId, email);
  const campaignRes = await app.request(`/api/v1/campaigns/${campaignId}`, {
    headers: bearer(ownerToken),
  });
  expect(campaignRes.status).toBe(200);
  const campaign = (await campaignRes.json()) as {
    members: Array<{ userId: string; email: string }>;
  };
  const member = campaign.members.find((item) => item.email === email);
  expect(member).toBeDefined();
  const promote = await app.request(`/api/v1/campaigns/${campaignId}/members/${member?.userId}`, {
    method: 'PATCH',
    headers: jsonHeaders(ownerToken),
    body: JSON.stringify({ role: 'manager' }),
  });
  expect(promote.status).toBe(200);
}

function historyFixture(args: {
  entityId: string;
  ownerId: string;
  campaignId: string;
  characterId: string | null;
  op?: string;
  batchId?: string | null;
  name: string;
}) {
  return {
    revision: sql<number>`nextval('revisions_seq')`,
    scope: 'character',
    entityClass: 'character',
    entityId: args.entityId,
    op: args.op ?? 'update',
    characterId: args.characterId,
    campaignId: args.campaignId,
    ownerUserId: args.ownerId,
    actorUserId: args.ownerId,
    batchId: args.batchId ?? null,
    oldRow: { name: `${args.name} old` },
    newRow: { name: args.name },
  };
}

async function createCharacter(
  accessToken: string,
  overrides: Record<string, unknown> = {},
): Promise<Record<string, unknown>> {
  const res = await app.request('/api/v1/characters', {
    method: 'POST',
    headers: jsonHeaders(accessToken),
    body: JSON.stringify({ name: `Character ${Date.now()}-${Math.random()}`, ...overrides }),
  });
  expect(res.status).toBe(201);
  return (await res.json()) as Record<string, unknown>;
}

type HistoryEvent = {
  id: string;
  revision: number;
  scope: string;
  characterId: string | null;
  entityClass: string;
  op: string;
  actorUserId: string | null;
  actorDisplayName: string | null;
  batchId: string | null;
  batchSize?: number;
  summary: string;
  oldRow?: Record<string, unknown> | null;
  newRow?: Record<string, unknown> | null;
};

// ===================== CHARACTER HISTORY =====================

describe('GET /characters/{id}/history', () => {
  it('owner sees every event generated by a sequence of REST edits, newest first', async () => {
    const owner = await registerUser('char-owner');
    const character = await createCharacter(owner.accessToken, { name: 'Chronicle' });

    await app.request(`/api/v1/characters/${character.id}`, {
      method: 'PATCH',
      headers: jsonHeaders(owner.accessToken),
      body: JSON.stringify({ name: 'Chronicle Renamed' }),
    });
    const traitRes = await app.request(`/api/v1/characters/${character.id}/traits`, {
      method: 'POST',
      headers: jsonHeaders(owner.accessToken),
      body: JSON.stringify({ kind: 'advantage', name: 'Luck' }),
    });
    const { trait } = (await traitRes.json()) as { trait: { id: string } };
    await app.request(`/api/v1/characters/${character.id}/traits/${trait.id}`, {
      method: 'PATCH',
      headers: jsonHeaders(owner.accessToken),
      body: JSON.stringify({ points: 15 }),
    });
    await app.request(`/api/v1/characters/${character.id}/traits/${trait.id}`, {
      method: 'DELETE',
      headers: bearer(owner.accessToken),
    });

    const res = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(owner.accessToken),
    });
    expect(res.status).toBe(200);
    const events = (await res.json()) as HistoryEvent[];
    // insert character, update character, insert trait, update trait, delete trait.
    expect(events.length).toBe(5);
    // Newest first.
    expect(events[0]?.op).toBe('delete');
    expect(events[0]?.entityClass).toBe('character_trait');
    expect(events[events.length - 1]?.op).toBe('insert');
    expect(events[events.length - 1]?.entityClass).toBe('character');
    for (const e of events) {
      expect(typeof e.summary).toBe('string');
      expect(e.summary.length).toBeGreaterThan(0);
      expect(e.actorDisplayName).toBe(owner.displayName);
    }
    // Descending revision order.
    for (let i = 1; i < events.length; i++) {
      const prev = events[i - 1];
      const curr = events[i];
      expect(prev).toBeDefined();
      expect(curr).toBeDefined();
      expect(prev?.revision).toBeGreaterThan(curr?.revision ?? Number.NaN);
    }
  });

  it('reports an explicit batch total on a later pagination page', async () => {
    const owner = await registerUser('char-hist-batch-page');
    const character = await createCharacter(owner.accessToken, { name: 'Batch Page Test' });
    const batchId = crypto.randomUUID();
    const ownerId = character.ownerId as string;

    await getDb()
      .insert(entityHistory)
      .values([
        {
          revision: sql<number>`nextval('revisions_seq')`,
          scope: 'character',
          entityClass: 'character',
          entityId: character.id as string,
          op: 'update',
          characterId: character.id as string,
          campaignId: null,
          ownerUserId: ownerId,
          actorUserId: ownerId,
          batchId,
          oldRow: { name: 'Batch Page Test' },
          newRow: { name: 'Batch Page Test 1' },
        },
        {
          revision: sql<number>`nextval('revisions_seq')`,
          scope: 'character',
          entityClass: 'character',
          entityId: character.id as string,
          op: 'update',
          characterId: character.id as string,
          campaignId: null,
          ownerUserId: ownerId,
          actorUserId: ownerId,
          batchId,
          oldRow: { name: 'Batch Page Test 1' },
          newRow: { name: 'Batch Page Test 2' },
        },
      ]);

    const firstPage = await app.request(`/api/v1/characters/${character.id}/history?limit=1`, {
      headers: bearer(owner.accessToken),
    });
    const firstEvents = (await firstPage.json()) as HistoryEvent[];
    expect(firstPage.status).toBe(200);
    expect(firstEvents).toHaveLength(1);

    const secondPage = await app.request(
      `/api/v1/characters/${character.id}/history?limit=1&before=${firstEvents[0]?.revision}`,
      { headers: bearer(owner.accessToken) },
    );
    const secondEvents = (await secondPage.json()) as HistoryEvent[];
    expect(secondPage.status).toBe(200);
    expect(secondEvents).toHaveLength(1);
    expect(secondEvents[0]?.batchId).toBe(batchId);
    expect(secondEvents[0]?.batchSize).toBe(2);
  });

  it('a member with minimal access (shareCharacterSheets=false) is denied (403)', async () => {
    const gm = await registerUser('char-hist-gm');
    const owner = await registerUser('char-hist-owner');
    const viewer = await registerUser('char-hist-viewer');
    const campaign = await createCampaign(gm.accessToken, { shareCharacterSheets: false });
    await addMember(gm.accessToken, campaign.id as string, owner.email);
    await addMember(gm.accessToken, campaign.id as string, viewer.email);
    const character = await createCharacter(owner.accessToken, {
      name: 'Hidden',
      campaignId: campaign.id,
    });

    const res = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(viewer.accessToken),
    });
    expect(res.status).toBe(403);
  });

  it('a member with full access (shareCharacterSheets=true) and the GM can both read history', async () => {
    const gm = await registerUser('char-hist-full-gm');
    const owner = await registerUser('char-hist-full-owner');
    const viewer = await registerUser('char-hist-full-viewer');
    const campaign = await createCampaign(gm.accessToken, { shareCharacterSheets: true });
    await addMember(gm.accessToken, campaign.id as string, owner.email);
    await addMember(gm.accessToken, campaign.id as string, viewer.email);
    const character = await createCharacter(owner.accessToken, {
      name: 'Visible',
      campaignId: campaign.id,
    });

    const viewerRes = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(viewer.accessToken),
    });
    expect(viewerRes.status).toBe(200);
    const viewerEvents = (await viewerRes.json()) as HistoryEvent[];
    expect(viewerEvents.length).toBeGreaterThan(0);

    const gmRes = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(gm.accessToken),
    });
    expect(gmRes.status).toBe(200);
  });

  it('a non-member of the campaign is denied (403)', async () => {
    const owner = await registerUser('char-hist-nonmember-owner');
    const outsider = await registerUser('char-hist-nonmember-outsider');
    const campaign = await createCampaign(owner.accessToken, { shareCharacterSheets: true });
    const character = await createCharacter(owner.accessToken, {
      name: 'Guarded',
      campaignId: campaign.id,
    });
    const res = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(outsider.accessToken),
    });
    expect(res.status).toBe(403);
  });

  it('a non-owner requesting a campaignless character is denied (403)', async () => {
    const owner = await registerUser('char-hist-solo-owner');
    const outsider = await registerUser('char-hist-solo-outsider');
    const character = await createCharacter(owner.accessToken, { name: 'Solo' });
    const res = await app.request(`/api/v1/characters/${character.id}/history`, {
      headers: bearer(outsider.accessToken),
    });
    expect(res.status).toBe(403);
  });

  it('404s for a nonexistent character', async () => {
    const owner = await registerUser('char-hist-404');
    const res = await app.request(
      '/api/v1/characters/00000000-0000-0000-0000-000000000000/history',
      { headers: bearer(owner.accessToken) },
    );
    expect(res.status).toBe(404);
  });
});

// ===================== CAMPAIGN HISTORY =====================

describe('GET /campaigns/{id}/history', () => {
  it('filters minimal-view manager history before pagination and batch counts, including deleted and departure mirrors', async () => {
    const owner = await registerUser('camp-hist-private-owner');
    const manager = await registerUser('camp-hist-private-manager');
    const otherPlayer = await registerUser('camp-hist-private-player');
    const campaign = await createCampaign(owner.accessToken, {
      shareCharacterSheets: false,
      allowGmCharacterEditing: false,
    });
    await addManager(owner.accessToken, campaign.id as string, manager.email);
    await addMember(owner.accessToken, campaign.id as string, otherPlayer.email);

    const hiddenCharacter = await createCharacter(otherPlayer.accessToken, {
      name: 'Deleted private character',
      campaignId: campaign.id,
    });
    const deniedCharacterHistory = await app.request(
      `/api/v1/characters/${hiddenCharacter.id}/history`,
      { headers: bearer(manager.accessToken) },
    );
    expect(deniedCharacterHistory.status).toBe(403);
    const deleteRes = await app.request(`/api/v1/characters/${hiddenCharacter.id}`, {
      method: 'DELETE',
      headers: bearer(otherPlayer.accessToken),
    });
    expect(deleteRes.status).toBe(204);

    const managerCharacter = await createCharacter(manager.accessToken, {
      name: 'Manager owned character',
      campaignId: campaign.id,
    });
    const campaignOwnerCharacter = await createCharacter(owner.accessToken, {
      name: 'Campaign owner own character',
      campaignId: campaign.id,
    });
    const managerBatchId = crypto.randomUUID();
    const managerHistoryRows = [
      historyFixture({
        entityId: managerCharacter.id as string,
        ownerId: managerCharacter.ownerId as string,
        campaignId: campaign.id as string,
        characterId: managerCharacter.id as string,
        batchId: managerBatchId,
        name: 'Manager owned change one',
      }),
      historyFixture({
        entityId: managerCharacter.id as string,
        ownerId: managerCharacter.ownerId as string,
        campaignId: campaign.id as string,
        characterId: managerCharacter.id as string,
        batchId: managerBatchId,
        name: 'Manager owned change two',
      }),
    ];
    await getDb().insert(entityHistory).values(managerHistoryRows);

    // Keep more than one page of hidden rows newer than the visible events.
    // The real delete above exercises a removed character whose history row
    // still has its character id. This NULL-id row models the campaign's
    // departure mirror for a character that left the campaign.
    const hiddenBatchId = managerBatchId;
    const hiddenRows = Array.from({ length: 24 }, (_, index) =>
      historyFixture({
        entityId: crypto.randomUUID(),
        ownerId: hiddenCharacter.ownerId as string,
        campaignId: campaign.id as string,
        characterId: index === 1 ? null : crypto.randomUUID(),
        op: 'update',
        batchId: index === 0 ? hiddenBatchId : null,
        name: index === 1 ? 'Departure mirror secret' : `Hidden row ${index}`,
      }),
    );
    await getDb().insert(entityHistory).values(hiddenRows);

    const pages: HistoryEvent[] = [];
    let before: number | undefined;
    for (let page = 0; page < 5; page++) {
      const query =
        before === undefined
          ? '?scope=character&detail=1&limit=1'
          : `?scope=character&detail=1&limit=1&before=${before}`;
      const res = await app.request(`/api/v1/campaigns/${campaign.id}/history${query}`, {
        headers: bearer(manager.accessToken),
      });
      expect(res.status).toBe(200);
      const events = (await res.json()) as HistoryEvent[];
      if (events.length === 0) break;
      pages.push(...events);
      before = events.at(-1)?.revision;
      if (events.length < 1) break;
    }

    expect(pages).toHaveLength(3);
    expect(pages.map((event) => (event.newRow as Record<string, unknown>)?.name)).toEqual([
      'Manager owned change two',
      'Manager owned change one',
      'Manager owned character',
    ]);
    expect(pages.slice(0, 2).every((event) => event.batchSize === 2)).toBe(true);
    const serialized = JSON.stringify(pages);
    expect(serialized).not.toContain('Deleted private character');
    expect(serialized).not.toContain('Departure mirror secret');
    expect(serialized).not.toContain('Hidden row');

    const summaryRes = await app.request(
      `/api/v1/campaigns/${campaign.id}/history?scope=character&limit=50`,
      { headers: bearer(manager.accessToken) },
    );
    expect(summaryRes.status).toBe(200);
    const summaryEvents = (await summaryRes.json()) as HistoryEvent[];
    expect(summaryEvents.some((event) => event.summary.includes('Manager owned character'))).toBe(
      true,
    );
    expect(summaryEvents.some((event) => event.summary.includes('Deleted private character'))).toBe(
      false,
    );
    expect(
      summaryEvents.every((event) => event.oldRow === undefined && event.newRow === undefined),
    ).toBe(true);

    const ownerRes = await app.request(
      `/api/v1/campaigns/${campaign.id}/history?scope=character&detail=1&limit=50`,
      { headers: bearer(owner.accessToken) },
    );
    expect(ownerRes.status).toBe(200);
    const ownerEvents = (await ownerRes.json()) as HistoryEvent[];
    expect(ownerEvents.some((event) => event.characterId === campaignOwnerCharacter.id)).toBe(true);
    expect(
      ownerEvents.some(
        (event) =>
          (event.newRow as Record<string, unknown> | null)?.name === 'Campaign owner own character',
      ),
    ).toBe(true);
  });

  it('campaign owners and managers with either full-view grant can read other character summaries and details', async () => {
    const owner = await registerUser('camp-hist-full-owner');
    const manager = await registerUser('camp-hist-full-manager');
    const player = await registerUser('camp-hist-full-player');
    for (const options of [
      { shareCharacterSheets: true, allowGmCharacterEditing: false },
      { shareCharacterSheets: false, allowGmCharacterEditing: true },
    ]) {
      const campaign = await createCampaign(owner.accessToken, options);
      await addManager(owner.accessToken, campaign.id as string, manager.email);
      await addMember(owner.accessToken, campaign.id as string, player.email);
      const character = await createCharacter(player.accessToken, {
        name: 'Shared character',
        campaignId: campaign.id,
      });
      const batchId = crypto.randomUUID();
      await getDb()
        .insert(entityHistory)
        .values([
          historyFixture({
            entityId: character.id as string,
            ownerId: character.ownerId as string,
            campaignId: campaign.id as string,
            characterId: character.id as string,
            batchId,
            name: 'Visible batch one',
          }),
          historyFixture({
            entityId: character.id as string,
            ownerId: character.ownerId as string,
            campaignId: campaign.id as string,
            characterId: character.id as string,
            batchId,
            name: 'Visible batch two',
          }),
        ]);

      for (const token of [owner.accessToken, manager.accessToken]) {
        const summaryRes = await app.request(
          `/api/v1/campaigns/${campaign.id}/history?scope=character&limit=50`,
          { headers: bearer(token) },
        );
        expect(summaryRes.status).toBe(200);
        const summaries = (await summaryRes.json()) as HistoryEvent[];
        expect(summaries.some((event) => event.characterId === character.id)).toBe(true);
        expect(summaries.some((event) => event.summary.includes('Shared character'))).toBe(true);

        const detailRes = await app.request(
          `/api/v1/campaigns/${campaign.id}/history?scope=character&detail=1&limit=50`,
          { headers: bearer(token) },
        );
        expect(detailRes.status).toBe(200);
        const details = (await detailRes.json()) as HistoryEvent[];
        const visibleBatch = details.filter((event) => event.batchId === batchId);
        expect(visibleBatch).toHaveLength(2);
        expect(visibleBatch.every((event) => event.batchSize === 2)).toBe(true);
        expect(
          visibleBatch.map((event) => (event.newRow as Record<string, unknown>)?.name),
        ).toEqual(['Visible batch two', 'Visible batch one']);
      }
    }
  });

  it('owner sees campaign-scope events, newest first, after a settings change', async () => {
    const owner = await registerUser('camp-hist-owner');
    const campaign = await createCampaign(owner.accessToken, { name: 'Original Name' });
    const patchRes = await app.request(`/api/v1/campaigns/${campaign.id}`, {
      method: 'PATCH',
      headers: jsonHeaders(owner.accessToken),
      body: JSON.stringify({ name: 'Renamed Campaign' }),
    });
    expect(patchRes.status).toBe(200);

    const res = await app.request(`/api/v1/campaigns/${campaign.id}/history`, {
      headers: bearer(owner.accessToken),
    });
    expect(res.status).toBe(200);
    const events = (await res.json()) as HistoryEvent[];
    // Campaign insert, owner membership, 16 seeded sources, then the rename.
    expect(events.length).toBe(19);
    expect(events[0]?.op).toBe('update');
    expect(events[0]?.entityClass).toBe('campaign');
    expect(events.every((e) => e.scope === 'campaign')).toBe(true);
    // No detail requested: oldRow/newRow are absent from the payload.
    expect(events[0]?.oldRow).toBeUndefined();
    expect(events[0]?.newRow).toBeUndefined();
  });

  it('?detail=1 includes oldRow/newRow snapshots; ?detail=false does NOT (only explicit truthy tokens enable it)', async () => {
    const owner = await registerUser('camp-hist-detail');
    const campaign = await createCampaign(owner.accessToken, { name: 'Detail Test' });
    await app.request(`/api/v1/campaigns/${campaign.id}`, {
      method: 'PATCH',
      headers: jsonHeaders(owner.accessToken),
      body: JSON.stringify({ name: 'Detail Test Renamed' }),
    });

    const detailRes = await app.request(`/api/v1/campaigns/${campaign.id}/history?detail=1`, {
      headers: bearer(owner.accessToken),
    });
    const detailEvents = (await detailRes.json()) as HistoryEvent[];
    const renameEvent = detailEvents.find((e) => e.op === 'update' && e.entityClass === 'campaign');
    expect(renameEvent).toBeDefined();
    expect(renameEvent?.oldRow).toBeTruthy();
    expect(renameEvent?.newRow).toBeTruthy();
    expect((renameEvent?.newRow as Record<string, unknown>).name).toBe('Detail Test Renamed');
    expect((renameEvent?.oldRow as Record<string, unknown>).name).toBe('Detail Test');

    // Pinning a deliberate quirk documented in the query-param schema: the
    // string "false" is truthy for a plain non-empty check, so a naive
    // coercion would turn ?detail=false into detail=true. The route uses an
    // explicit allow-list ('1' | 'true' | 'yes'), so "false" stays OFF.
    const falseDetailRes = await app.request(
      `/api/v1/campaigns/${campaign.id}/history?detail=false`,
      { headers: bearer(owner.accessToken) },
    );
    const falseDetailEvents = (await falseDetailRes.json()) as HistoryEvent[];
    expect(falseDetailEvents[0]?.oldRow).toBeUndefined();
    expect(falseDetailEvents[0]?.newRow).toBeUndefined();
  });

  it('before pagination walks older pages without gaps or overlaps', async () => {
    const owner = await registerUser('camp-hist-page');
    const campaign = await createCampaign(owner.accessToken, { name: 'Page Test' });
    // 3 updates on top of the campaign, membership, and 16 source inserts.
    for (let i = 0; i < 3; i++) {
      await app.request(`/api/v1/campaigns/${campaign.id}`, {
        method: 'PATCH',
        headers: jsonHeaders(owner.accessToken),
        body: JSON.stringify({ name: `Page Test ${i}` }),
      });
    }

    const seen: HistoryEvent[] = [];
    let before: number | undefined;
    for (let page = 0; page < 20; page++) {
      const url = before
        ? `/api/v1/campaigns/${campaign.id}/history?limit=2&before=${before}`
        : `/api/v1/campaigns/${campaign.id}/history?limit=2`;
      const res = await app.request(url, { headers: bearer(owner.accessToken) });
      expect(res.status).toBe(200);
      const events = (await res.json()) as HistoryEvent[];
      if (events.length === 0) break;
      seen.push(...events);
      before = events[events.length - 1]?.revision;
      if (events.length < 2) break;
    }

    expect(seen.length).toBe(21);
    const ids = seen.map((e) => e.id);
    expect(new Set(ids).size).toBe(21); // no duplicates across pages.
    for (let i = 1; i < seen.length; i++) {
      const prev = seen[i - 1];
      const curr = seen[i];
      expect(prev).toBeDefined();
      expect(curr).toBeDefined();
      expect(prev?.revision).toBeGreaterThan(curr?.revision ?? Number.NaN);
    }
  });

  it('scope=character is GM-only: the owner can request it, a plain member is denied (403)', async () => {
    const gm = await registerUser('camp-hist-scope-gm');
    const player = await registerUser('camp-hist-scope-player');
    const campaign = await createCampaign(gm.accessToken);
    await addMember(gm.accessToken, campaign.id as string, player.email);
    const character = await createCharacter(player.accessToken, {
      name: 'Player Character',
      campaignId: campaign.id,
    });
    await app.request(`/api/v1/characters/${character.id}`, {
      method: 'PATCH',
      headers: jsonHeaders(player.accessToken),
      body: JSON.stringify({ name: 'Player Character Renamed' }),
    });

    const gmRes = await app.request(`/api/v1/campaigns/${campaign.id}/history?scope=character`, {
      headers: bearer(gm.accessToken),
    });
    expect(gmRes.status).toBe(200);
    const gmEvents = (await gmRes.json()) as HistoryEvent[];
    expect(gmEvents.every((e) => e.scope === 'character')).toBe(true);
    expect(gmEvents.some((e) => e.entityClass === 'character')).toBe(true);

    const playerRes = await app.request(
      `/api/v1/campaigns/${campaign.id}/history?scope=character`,
      { headers: bearer(player.accessToken) },
    );
    expect(playerRes.status).toBe(403);
  });

  it('a non-member is denied (403)', async () => {
    const owner = await registerUser('camp-hist-nonmember-owner');
    const outsider = await registerUser('camp-hist-nonmember-outsider');
    const campaign = await createCampaign(owner.accessToken);
    const res = await app.request(`/api/v1/campaigns/${campaign.id}/history`, {
      headers: bearer(outsider.accessToken),
    });
    expect(res.status).toBe(403);
  });
});
